version: 2.1
orbs:
  nx: nrwl/nx@1.6.0
jobs:
  build:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  lint:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run: npm install
      - run: nx run lint

workflows:
  version: 2
  pr-commit:
    jobs:
      - build:
          name: build
      - lint:
          name: lint
          requires: [build]
